apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
  - image: k8s-back-end-image
    context: server
    docker:
      dockerfile: development/Dockerfile
  - image: k8s-front-end-image
    context: client
    docker:
      dockerfile: development/Dockerfile
  local:
    push: false
    useBuildkit: true
deploy:
  kubectl:
    manifests:
      - infra/development/k8s/front_end.yaml
      - infra/development/k8s/backend_end.yaml
