apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
  - image: k8s-back-end-image
    context: server
    docker:
      dockerfile: development/Dockerfile
      buildArgs:
        DB_HOST: local-postgres-svc
        DB_PORT: "15432"
        DB_USER: postgres
        DB_DATEBASE: elixir_dev
        DB_PASSWORD: postgres
        PORT: "8080"
  - image: k8s-front-end-image
    context: client
    docker:
      dockerfile: development/Dockerfile
  local:
    push: false
deploy:
  kubectl:
    manifests:
      - infra/development/k8s/front_end.yaml
      - infra/development/k8s/backend_end.yaml
