apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: local-postgres-svc
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 15432
      targetPort: 5432
  selector:
    app: local-postgres-pod

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-postgres-deploy
spec:
  selector:
    matchLabels:
      app: local-postgres-pod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: local-postgres-pod
    spec:
      containers:
        - name: local-postgres-container
          image: postgres:9.6
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_HOST
              value: postgres-host
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim
