apiVersion: v1
kind: Service
metadata:
  name: swagger-editor-svc
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: swagger-editor-pod

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-editor-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger-editor-pod
  template:
    metadata:
      labels:
        app: swagger-editor-pod
    spec:
      containers:
        - name: swagger-editor-container
          image: swaggerapi/swagger-editor:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
